--- 
- name: Install dependencies
  apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: yes

- name: Install Samaba 
  apt:
    name: samba
    state: latest
  when: smb_enabled == "true"
